### ISSUE TITLE
Not working on iOS 10.1.1?

### ISSUE THREAD

**Issue by Tatsh** [Sticktron/SSHIcon#1]
iOS 10.1.1 on iPhone 7 Plus

I have ensured that I set up settings including setting an icon, respring'd, and I connected both via iproxy (SSH over USB) and via normal IP address connection. No icon on the status bar displays.

Could you update the README on building? I can build except for `SSHIconSettings`:

```
> Making all for tweak SSHIconUI…
make[2]: Nothing to be done for `internal-library-compile'.
> Making all for tweak SSHIconSB…
make[2]: Nothing to be done for `internal-library-compile'.
> Making all in Settings…
> Making all for bundle SSHIconSettings…
==> Copying resource directories into the bundle wrapper…
==> Compiling SSHIconSettingsController.m (armv7)…
==> Linking bundle SSHIconSettings (armv7)…
ld: framework not found Preferences
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [/Users/tatsh/dev/tweaks/SSHIcon/.theos/obj/debug/armv7/SSHIconSettings.bundle/SSHIconSettings] Error 1
make[3]: *** [/Users/tatsh/dev/tweaks/SSHIcon/.theos/obj/debug/armv7/SSHIconSettings.bundle/SSHIconSettings] Error 2
make[2]: *** [internal-bundle-all_] Error 2
make[1]: *** [SSHIconSettings.all.bundle.variables] Error 2
make: *** [internal-all] Error
```

**Comment by Sticktron** [comment]
Which libstatusbar variant do you have installed: libstatusbar, libmoorecon, or libstatus9?

Re: compiling: you need a copy of an iOS SDK with private framework symbols.
You can download the 10.1 (and 9.3) SDKs here: https://github.com/Sticktron/sdks

Put them in $THEOS/sdks/

**Comment by Tatsh** [comment]
I realised libstatusbar was not installed. That package pulls in libstatus9. Tried that and no luck. Then I removed that and tried libmoorecon and no luck. Have you tried this with Dropbear as opposed to OpenSSH? Dropbear is what comes with the current 10.x jailbreaks. I have not yet tried using OpenSSH.

**Comment by Tatsh** [comment]
I am getting this in my syslog:

```
Sep  1 12:46:29 copula com.apple.WebKit.WebContent[13553] <Warning>: MS:Warning: message not found [SSHIconItemView initWithItem:data:actions:style:]
Sep  1 12:46:29 copula com.apple.WebKit.WebContent[13553] <Warning>: MS:Warning: message not found [SSHIconItemView contentsImage]
Sep  1 12:46:29 copula com.apple.WebKit.WebContent[13553] <Warning>: MS:Warning: message not found [SSHIconItemView updateContentsAndWidth]
```

Wants to draw, but the method calls fail for some reason.

**Comment by Tatsh** [comment]
Figured it out. This does not work with Dropbear because that server does not update the database at `/var/run/utmpx`.

**Comment by Packetfahrer** [comment]
Just testet with an 7+ installed from Cydia, works! 

On the first run i have to set the Style.

**Comment by Tatsh** [comment]
Well this bug is really just that the out-of-box SSH included with extra_recipe does not work with this. This package only works when you use OpenSSH server. I don't know the best way to handle dropbear although I could see searching the process list for it and getting the user name that way. The host would be unknown but maybe can be seen in the network connections (netstat).

**Comment by Packetfahrer** [comment]
@Tatsh i have installed SCP and SFTP for dropbear (from Coolstar´s Repo). this installs OpenSSL i think.

**Comment by Sticktron** [comment]
@Tatsh I have tested it with both Dropbear and OpenSSH, and both are working correctly for me.

**Comment by Sticktron** [comment]
@Packetfahrer That bug is now fixed in 1.0.1

**Comment by Tatsh** [comment]
I switched to a stable release of yalu+extra_recipe. Works now with Dropbear.

**Comment by Sticktron** [comment]
@Tatsh Thanks for following up.
